// apps/web-vue/src/components/LayoutAside/SettingsDialog.vue
<template>
    <NModal v-model:show="modelOpen" preset="card" style="width: 480px" title="设置" @update:show="onOpenChange">
        <div class="settings-content">
            <div class="setting-item">
                <span class="setting-label">用户名</span>
                <span class="setting-value">{{ username || '—' }}</span>
            </div>
            <div class="setting-item">
                <span class="setting-label">主题</span>
                <div class="theme-options">
                    <button
                        v-for="option in themeOptions"
                        :key="option.value"
                        :class="['theme-btn', { active: theme === option.value }]"
                        @click="setTheme(option.value)"
                    >
                        {{ option.label }}
                    </button>
                </div>
            </div>
        </div>
    </NModal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { NModal } from 'naive-ui'

type Theme = 'light' | 'dark' | 'system'

interface Props {
    open: boolean
    onOpenChange: (open: boolean) => void
    username?: string
}

const props = defineProps<Props>()
const emit = defineEmits<{
    'update:open': [value: boolean]
}>()

const modelOpen = computed({
    get: () => props.open,
    set: (val: boolean) => {
        emit('update:open', val)
        props.onOpenChange(val)
    },
})

const themeOptions = [
    { value: 'light' as Theme, label: '浅色' },
    { value: 'dark' as Theme, label: '深色' },
    { value: 'system' as Theme, label: '跟随系统' },
]

function getStoredTheme(): Theme {
    return (localStorage.getItem('lcwdoc-theme') as Theme) || 'system'
}

const theme = ref<Theme>(getStoredTheme())

function applyTheme(t: Theme) {
    const isDark = t === 'dark' || (t === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)
    document.documentElement.classList.toggle('dark', isDark)
}

function setTheme(t: Theme) {
    theme.value = t
    localStorage.setItem('lcwdoc-theme', t)
    applyTheme(t)
}

watch(theme, (t) => {
    applyTheme(t)
})

// Track system theme changes
if (typeof window !== 'undefined') {
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {
        if (theme.value === 'system') {
            applyTheme('system')
        }
    })
}
</script>

<style scoped>
.settings-content {
    display: flex;
    flex-direction: column;
    gap: 16px;
}

.setting-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 0;
    border-bottom: 1px solid #e9e9e7;
}

.setting-label {
    font-size: 14px;
    color: #787774;
}

.setting-value {
    font-size: 14px;
    font-weight: 500;
    color: #37352f;
}

.theme-options {
    display: flex;
    border-radius: 8px;
    overflow: hidden;
    border: 1px solid #e9e9e7;
}

.theme-btn {
    padding: 6px 12px;
    font-size: 12px;
    border: none;
    cursor: pointer;
    background: white;
    color: #787774;
    transition: all 0.15s;
}

.theme-btn:hover {
    background: #f5f5f4;
}

.theme-btn.active {
    background: #37352f;
    color: white;
}
</style>

// apps/web/src/components/LayoutAside/SettingsDialog.tsx
import * as Dialog from '@radix-ui/react-dialog'
import { useEffect, useState } from 'react'

type Theme = 'light' | 'dark' | 'system'

function applyTheme(theme: Theme) {
    const isDark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)
    if (isDark) {
        document.documentElement.classList.add('dark')
    } else {
        document.documentElement.classList.remove('dark')
    }
}

function getStoredTheme(): Theme {
    return (localStorage.getItem('lcwdoc-theme') as Theme) || 'system'
}

function setStoredTheme(theme: Theme) {
    localStorage.setItem('lcwdoc-theme', theme)
}

const themeOptions: { value: Theme; label: string }[] = [
    { value: 'light', label: '浅色' },
    { value: 'dark', label: '深色' },
    { value: 'system', label: '跟随系统' },
]

interface SettingsDialogProps {
    open: boolean
    onOpenChange: (open: boolean) => void
    username?: string
}

export function SettingsDialog({ open, onOpenChange, username }: SettingsDialogProps) {
    const [theme, setTheme] = useState<Theme>(getStoredTheme)

    useEffect(() => {
        applyTheme(theme)
        setStoredTheme(theme)
    }, [theme])

    useEffect(() => {
        if (theme !== 'system') return
        const mql = window.matchMedia('(prefers-color-scheme: dark)')
        const handler = () => applyTheme('system')
        mql.addEventListener('change', handler)
        return () => mql.removeEventListener('change', handler)
    }, [theme])

    return (
        <Dialog.Root open={open} onOpenChange={onOpenChange}>
            <Dialog.Portal>
                <Dialog.Overlay className="fixed inset-0 z-50 bg-black/50" />
                <Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-full max-w-md -translate-x-1/2 -translate-y-1/2 rounded-xl bg-white p-6 shadow-2xl">
                    <Dialog.Title className="sr-only">设置</Dialog.Title>
                    <Dialog.Description className="sr-only">应用设置面板</Dialog.Description>

                    <h2 className="text-lg font-semibold mb-6 text-[#37352f]">设置</h2>

                    <div className="space-y-6">
                        <div>
                            <div className="flex justify-between items-center py-3 border-b border-[#e9e9e7]">
                                <span className="text-sm text-[#787774]">用户名</span>
                                <span className="text-sm font-medium text-[#37352f]">{username ?? '—'}</span>
                            </div>
                        </div>

                        <div>
                            <div className="flex justify-between items-center py-3 border-b border-[#e9e9e7]">
                                <span className="text-sm text-[#787774]">语言设置</span>
                                <span className="text-sm font-medium text-[#37352f]">中文</span>
                            </div>
                            <div className="flex justify-between items-center py-3 border-b border-[#e9e9e7]">
                                <span className="text-sm text-[#787774]">主题</span>
                                <div className="flex rounded-lg overflow-hidden border border-[#e9e9e7]">
                                    {themeOptions.map(option => (
                                        <button
                                            key={option.value}
                                            onClick={() => setTheme(option.value)}
                                            className={`px-3 py-1 text-xs transition-colors ${
                                                theme === option.value
                                                    ? 'bg-[#37352f] text-white'
                                                    : 'bg-white text-[#787774] hover:bg-[#f5f5f4]'
                                            }`}
                                        >
                                            {option.label}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </Dialog.Content>
            </Dialog.Portal>
        </Dialog.Root>
    )
}
