// apps/web/src/pages/DocGraph/index.tsx
import '@xyflow/react/dist/style.css'

import { SidebarInset, SidebarTrigger } from '@lcw-doc/shadcn-shared-ui/components/ui/sidebar'
import { useQuery } from '@tanstack/react-query'
import { applyEdgeChanges, applyNodeChanges, Background, Controls, Edge, EdgeChange, MiniMap, Node, NodeChange, ReactFlow } from '@xyflow/react'
import * as d3 from 'd3-force'
import { FileText, GitBranch, Loader } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'

import * as srv from '@/services'

import { GraphEdge } from './Edge'
import { GraphNode } from './Node'

const nodesTypes = {
    graph: GraphNode,
}

const edgeTypes = {
    graph: GraphEdge,
}

export function DocGraph() {
    const [nodes, setNodes] = useState<Node[]>([])
    const [edges, setEdges] = useState<Edge[]>([])
    const [simulationReady, setSimulationReady] = useState(false)
    const navigate = useNavigate()
    const pagesRef = useRef<string>('')

    const { data: pages = [], isLoading } = useQuery({
        queryKey: ['pageGraph'],
        queryFn: async () => {
            return (await srv.fetchPageGraph()).data
        },
    })

    const pagesKey = pages.map(p => `${p.pageId}:${(p.links || []).join(',')}`).join('|')
    const edgeCount = pages.reduce((count, page) => count + (page.links || []).length, 0)

    const handleNodeClick = (_: React.MouseEvent, node: Node) => {
        const { id } = node
        setNodes(nds => nds.map(n => ({ ...n, selected: n.id === id })))
        setEdges(eds => eds.map(e => ({ ...e, selected: e.source === id || e.target === id })))
    }

    const handleNodeDoubleClick = (_: React.MouseEvent, node: Node) => {
        navigate(`/doc/${node.id}`)
    }

    const handlePaneClick = () => {
        setNodes(nds => nds.map(n => ({ ...n, selected: false })))
        setEdges(eds => eds.map(e => ({ ...e, selected: false })))
    }

    const onNodesChange = (changes: NodeChange[]) => setNodes(nds => applyNodeChanges(changes, nds))
    const onEdgesChange = (changes: EdgeChange[]) => setEdges(eds => applyEdgeChanges(changes, eds))

    useEffect(() => {
        if (pagesRef.current === pagesKey) return
        pagesRef.current = pagesKey

        if (pages.length === 0) {
            setNodes([])
            setEdges([])
            setSimulationReady(true)
            return
        }

        setSimulationReady(false)

        const initialNodes = pages.map(page => {
            return {
                id: page.pageId,
                type: 'graph',
                data: {
                    emoji: page.emoji,
                    title: page.title,
                },
                width: 120,
                height: 80,
                x: 0,
                y: 0,
            }
        })

        const initialEdges = []
        for (let pi = 0; pi < pages.length; pi++) {
            const page = pages[pi]
            for (const link of page.links || []) {
                const targetIndex = pages.findIndex(p => p.pageId === link)
                if (targetIndex === -1) {
                    continue
                }
                initialEdges.push({
                    id: `${page.pageId}-${link}`,
                    data: {
                        label: '@提及',
                    },
                    source: pi,
                    target: targetIndex,
                })
            }
        }

        const simulation = d3
            .forceSimulation(initialNodes)
            .force('charge', d3.forceManyBody().strength(-120))
            .force('collide', d3.forceCollide(100))
            .force('link', d3.forceLink(initialEdges).strength(0.5).distance(200).iterations(100))
            .force('center', d3.forceCenter(500, 350))
            .force('radial', d3.forceRadial(150, 500, 350).strength(0.3))

        simulation.on('end', () => {
            setSimulationReady(true)
        })

        simulation.on('tick', () => {
            const forceNodes = simulation.nodes().map(node => ({ ...node, position: { x: node.x, y: node.y } }))
            setNodes(forceNodes)
        })

        // @ts-expect-error force edge type
        const flowEdges = initialEdges.map(edge => ({ ...edge, type: 'graph', source: edge?.source.id, target: edge?.target.id }))
        setEdges(flowEdges)

        return () => {
            simulation.stop()
        }
    }, [pages, pagesKey])

    const isEmpty = pages.length === 0
    const hasNoLinks = !isEmpty && edgeCount === 0

    return (
        <SidebarInset>
            <div className="flex flex-col w-full h-full">
                <div className="flex flex-row items-center justify-between p-6 gap-2">
                    <div className="flex flex-row items-center gap-2">
                        <SidebarTrigger />
                        <h1 className="text-xl text-zinc-500">文档图谱</h1>
                    </div>
                    {!isEmpty && (
                        <div className="flex items-center gap-4 text-sm text-zinc-400">
                            <span className="flex items-center gap-1">
                                <FileText className="w-4 h-4" />
                                {pages.length} 篇文档
                            </span>
                            <span className="flex items-center gap-1">
                                <GitBranch className="w-4 h-4" />
                                {edgeCount} 条关联
                            </span>
                        </div>
                    )}
                </div>
                <div className="w-full h-full relative">
                    {(isLoading || !simulationReady) && (
                        <div className="w-full h-full flex justify-center items-center bg-zinc-50/30 absolute z-10">
                            <div className="flex flex-col items-center gap-2">
                                <Loader className="w-8 h-8 animate-spin text-zinc-400" />
                                <p className="text-sm text-zinc-400">
                                    {isLoading ? '加载中...' : '布局计算中...'}
                                </p>
                            </div>
                        </div>
                    )}
                    {isEmpty && simulationReady && (
                        <div className="w-full h-full flex justify-center items-center">
                            <div className="flex flex-col items-center gap-3 text-zinc-400">
                                <FileText className="w-12 h-12" />
                                <p className="text-lg font-medium">暂无文档</p>
                                <p className="text-sm">创建文档并使用 @提及 来建立关联</p>
                            </div>
                        </div>
                    )}
                    {hasNoLinks && simulationReady && (
                        <div className="w-full h-full">
                            <ReactFlow
                                nodesDraggable
                                proOptions={{ hideAttribution: true }}
                                nodes={nodes}
                                edges={edges}
                                nodeTypes={nodesTypes}
                                edgeTypes={edgeTypes}
                                onNodeClick={handleNodeClick}
                                onNodeDoubleClick={handleNodeDoubleClick}
                                onPaneClick={handlePaneClick}
                                onNodesChange={onNodesChange}
                                onEdgesChange={onEdgesChange}
                                fitView
                            >
                                <Background />
                                <Controls />
                                <MiniMap
                                    nodeStrokeWidth={3}
                                    pannable
                                    zoomable
                                />
                            </ReactFlow>
                            <div className="absolute top-4 left-1/2 -translate-x-1/2 z-10 bg-white/80 backdrop-blur-sm px-4 py-2 rounded-full text-sm text-zinc-500 shadow-sm">
                                暂无文档关联，在文档中使用 @提及 其他文档来建立关联
                            </div>
                        </div>
                    )}
                    {!isEmpty && !hasNoLinks && (
                        <ReactFlow
                            nodesDraggable
                            proOptions={{ hideAttribution: true }}
                            nodes={nodes}
                            edges={edges}
                            nodeTypes={nodesTypes}
                            edgeTypes={edgeTypes}
                            onNodeClick={handleNodeClick}
                            onNodeDoubleClick={handleNodeDoubleClick}
                            onPaneClick={handlePaneClick}
                            onNodesChange={onNodesChange}
                            onEdgesChange={onEdgesChange}
                            fitView
                        >
                            <Background />
                            <Controls />
                            <MiniMap
                                nodeStrokeWidth={3}
                                pannable
                                zoomable
                            />
                        </ReactFlow>
                    )}
                </div>
            </div>
        </SidebarInset>
    )
}

// apps/web-vue/src/views/DocGraph/index.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useQuery } from '@tanstack/vue-query'
import { VueFlow, type Node, type Edge } from '@vue-flow/core'
import { Background } from '@vue-flow/background'
import { Controls } from '@vue-flow/controls'
import { MiniMap } from '@vue-flow/minimap'
import '@vue-flow/core/dist/style.css'
import '@vue-flow/core/dist/theme-default.css'
import '@vue-flow/controls/dist/style.css'
import '@vue-flow/minimap/dist/style.css'
import * as d3 from 'd3-force'
import { NButton, NSpin } from 'naive-ui'
import { FileText, GitBranch } from 'lucide-vue-next'

import * as srv from '@/services'

const router = useRouter()

const nodes = ref<Node[]>([])
const edges = ref<Edge[]>([])
const simulationReady = ref(false)

const { data: pages = [], isLoading } = useQuery({
    queryKey: ['pageGraph'],
    queryFn: async () => {
        return (await srv.fetchPageGraph()).data
    },
})

let simulation: d3.Simulation<any, any> | null = null
let pagesKey = ''

function buildGraph() {
    const newKey = pages.value.map((p: any) => `${p.pageId}:${(p.links || []).join(',')}`).join('|')
    if (pagesKey === newKey) return
    pagesKey = newKey

    if (pages.value.length === 0) {
        nodes.value = []
        edges.value = []
        simulationReady.value = true
        return
    }

    simulationReady.value = false

    const initialNodes = pages.value.map((page: any, i: number) => ({
        id: page.pageId,
        type: 'default',
        data: {
            label: `${page.emoji || '📄'} ${page.title}`,
        },
        position: { x: 0, y: 0 },
        draggable: true,
    }))

    const initialEdges: any[] = []
    for (const page of pages.value) {
        for (const link of page.links || []) {
            if (pages.value.find((p: any) => p.pageId === link)) {
                initialEdges.push({
                    id: `${page.pageId}-${link}`,
                    source: page.pageId,
                    target: link,
                    type: 'default',
                    animated: false,
                })
            }
        }
    }

    // d3-force layout
    simulation = d3
        .forceSimulation(initialNodes.map((n: any) => ({ ...n })))
        .force('charge', d3.forceManyBody().strength(-120))
        .force('collide', d3.forceCollide(100))
        .force('link', d3.forceLink(initialEdges).strength(0.5).distance(200).iterations(100))

    simulation.on('end', () => {
        simulationReady.value = true
    })

    simulation.on('tick', () => {
        if (!simulation) return
        const simNodes = simulation.nodes()
        const updatedNodes = (nodes.value as any[]).length === 0
            ? initialNodes.map((n: any, i: number) => ({
                ...n,
                position: { x: simNodes[i]?.x || 0, y: simNodes[i]?.y || 0 },
            }))
            : nodes.value.map((n: any, i: number) => ({
                ...n,
                position: { x: simNodes[i]?.x || 0, y: simNodes[i]?.y || 0 },
            }))
        nodes.value = updatedNodes as any
    })

    // Set edges
    edges.value = initialEdges as Edge[]
    nodes.value = initialNodes as Node[]
}

// Watch for page changes
let pagesWatchStop: (() => void) | undefined

onMounted(() => {
    pagesWatchStop = watch(pages, () => buildGraph(), { deep: true, immediate: true })
})

onBeforeUnmount(() => {
    simulation?.stop()
    simulation = null
    pagesWatchStop?.()
})

const edgeCount = ref(0)

watch(pages, (val) => {
    edgeCount.value = val.reduce((count: number, page: any) => count + (page.links || []).length, 0)
}, { immediate: true })

function handleNodeClick({ node }: { node: Node }) {
    nodes.value = nodes.value.map((n) => ({ ...n, selected: n.id === node.id })) as any
    edges.value = edges.value.map((e) => ({ ...e, selected: e.source === node.id || e.target === node.id })) as any
}

function handleNodeDoubleClick({ node }: { node: Node }) {
    router.push(`/doc/${node.id}`)
}

function handlePaneClick() {
    nodes.value = nodes.value.map((n) => ({ ...n, selected: false })) as any
    edges.value = edges.value.map((e) => ({ ...e, selected: false })) as any
}

const isEmpty = computed(() => pages.value.length === 0)
const hasNoLinks = computed(() => !isEmpty.value && edgeCount.value === 0)
</script>

<template>
    <div class="docgraph-page">
        <!-- Header -->
        <div class="docgraph-header">
            <h1 class="docgraph-title">文档图谱</h1>
            <div v-if="!isEmpty" class="docgraph-stats">
                <span class="stat-item">
                    <FileText :size="16" />
                    {{ pages.length }} 篇文档
                </span>
                <span class="stat-item">
                    <GitBranch :size="16" />
                    {{ edgeCount }} 条关联
                </span>
            </div>
        </div>

        <!-- Graph area -->
        <div class="docgraph-canvas">
            <!-- Loading overlay -->
            <div v-if="isLoading || !simulationReady" class="docgraph-loading">
                <NSpin />
                <p>{{ isLoading ? '加载中...' : '布局计算中...' }}</p>
            </div>

            <!-- Empty state -->
            <div v-if="isEmpty && simulationReady" class="docgraph-empty">
                <FileText :size="48" />
                <p class="empty-title">暂无文档</p>
                <p class="empty-desc">创建文档并使用 @提及 来建立关联</p>
            </div>

            <!-- Graph -->
            <template v-if="!isEmpty && simulationReady">
                <VueFlow
                    :nodes="nodes"
                    :edges="edges"
                    :node-click-distance="5"
                    fit-view-on-init
                    @node-click="handleNodeClick"
                    @node-double-click="handleNodeDoubleClick"
                    @pane-click="handlePaneClick"
                >
                    <Background />
                    <Controls />
                    <MiniMap node-stroke-width="3" pannable zoomable />
                </VueFlow>

                <div v-if="hasNoLinks" class="no-links-hint">
                    暂无文档关联，在文档中使用 @提及 其他文档来建立关联
                </div>
            </template>
        </div>
    </div>
</template>

<style scoped>
.docgraph-page {
    height: 100%;
    display: flex;
    flex-direction: column;
    background: hsl(var(--background));
}

.docgraph-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 24px 32px 0;
    flex-shrink: 0;
}

.docgraph-title {
    font-size: 26px;
    font-weight: 700;
    color: hsl(var(--foreground));
    margin: 0;
    letter-spacing: -0.02em;
}

.docgraph-stats {
    display: flex;
    align-items: center;
    gap: 16px;
    font-size: 13px;
    color: hsl(var(--muted-foreground));
}

.stat-item {
    display: inline-flex;
    align-items: center;
    gap: 6px;
}

.docgraph-canvas {
    flex: 1;
    position: relative;
    margin: 16px 32px 24px;
    border-radius: 12px;
    overflow: hidden;
    border: 1px solid hsl(var(--border));
    background: hsl(var(--card));
    min-height: 300px;
}

.docgraph-loading {
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 10px;
    z-index: 10;
    color: hsl(var(--muted-foreground));
    font-size: 14px;
    background: hsl(var(--card));
}

.docgraph-empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    min-height: 300px;
    color: hsl(var(--muted-foreground));
    gap: 8px;
}

.empty-title {
    font-size: 16px;
    font-weight: 600;
    margin: 12px 0 0;
    color: hsl(var(--foreground));
}

.empty-desc {
    font-size: 13px;
    margin: 0;
}

.no-links-hint {
    position: absolute;
    top: 16px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 10;
    background: hsl(var(--card) / 0.9);
    backdrop-filter: blur(6px);
    padding: 8px 16px;
    border-radius: 999px;
    font-size: 13px;
    color: hsl(var(--muted-foreground));
    box-shadow: 0 1px 4px hsl(var(--foreground) / 0.08);
    white-space: nowrap;
    border: 1px solid hsl(var(--border));
}
</style>
